# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  NAMESPACE: klementevtech
  APP: gotips
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null | sed 's/^v//' || echo "unknown"

  IMAGE: '{{.NAMESPACE}}/{{.APP}}'
  IMAGE_TAGGED: '{{.IMAGE}}:{{.VERSION}}'
  IMAGE_LATEST: '{{.IMAGE}}:latest'

  DB_DRIVER: sqlite3
  DB_NAME: 'sqlite3/data/gotips.db'
  MIGRATIONS_DIR: 'migrations/schema'

  GOLANGCI_VERSION: v2.11.4
  BUF_VERSION: v1.68.4

tasks:
  default:
    desc: "Листинг команд"
    cmds:
      - task --list
    silent: true

  build:
    desc: "Собирает Docker образ"
    cmds:
      - |
        docker build \
          -f $(pwd)/docker/Dockerfile \
          --build-arg VERSION={{.VERSION}} \
          -t "{{.IMAGE_TAGGED}}" \
          -t "{{.IMAGE_LATEST}}" \
          .

  run:
    desc: "Запуск Docker образа"
    cmds:
      - |
        docker run -d \
          --name gotips \
          -p 50051:50051 \
          -p 6060:6060 \
          -v $(pwd)/config/config.dev.toml:/etc/gotips/config.toml:ro \
          -v $(pwd)/sqlite3/data:/data/gotips:rw \
          klementevtech/gotips:latest

  lint:
    desc: "Проверка линтером"
    cmds:
      - golangci-lint run ./...

  lint-fix:
    desc: "Форматирование линтером"
    cmds:
      - golangci-lint run --fix

  format:
    desc: "Форматирование"
    cmds:
      - gofumpt -l -w .

  test:
    desc: "Запуск тестов"
    cmds:
      - go test -v ./...

  tidy:
    desc: "Очистка зависимостей"
    cmds:
      - go mod tidy

  pre-commit:
    desc: "Запуск проверок перед коммитом"
    cmds:
      - cmd: echo "Форматирование..."
        silent: true
      - task: format

      - cmd: echo "Форматирование линтером..."
        silent: true
      - task: lint-fix

      - cmd: echo "Проверка линтером..."
        silent: true
      - task: lint

      - cmd: echo "Проверка proto файлов..."
        silent: true
      - task: lint-proto

      - cmd: echo "Запуск тестов..."
        silent: true
      - task: test

      - cmd: echo "Очистка зависимостей..."
        silent: true
      - task: tidy

      - cmd: echo "[OK] Все проверки пройдены."
        silent: true

  gen-pb:
    desc: "Генерирует protobuf файлы"
    cmds:
      - buf generate

  lint-proto:
    desc: "Проверка proto файлов"
    cmds:
      - buf lint

  lint-proto-changes:
    desc: "Проверка обратной совместимости proto файлов"
    cmds:
      - buf breaking --against ".git#branch=main"

  migrate-new:
    desc: "Создать миграцию. Пример: task migrate-new name=add_parts"
    vars:
      NAME: '{{.name | default "migration"}}'
    cmds:
      - goose {{.DB_DRIVER}} {{.DB_NAME}} -dir {{.MIGRATIONS_DIR}} create {{.NAME}} sql
    preconditions:
      - sh: 'test -n "{{.NAME}}"'
        msg: "Ошибка: нужно указать имя. Используй: task create-migration name=имя_миграции"

  migrate-up:
    desc: "Накатить миграции SQLite"
    cmds:
      - goose {{.DB_DRIVER}} {{.DB_NAME}} -dir {{.MIGRATIONS_DIR}} up

  migrate-down:
    desc: "Откатить последнюю миграцию"
    cmds:
      - goose {{.DB_DRIVER}} {{.DB_NAME}} -dir {{.MIGRATIONS_DIR}} down

  migrate-reset:
    desc: "Сбросить ВСЮ базу (удалить все таблицы)"
    cmds:
      - goose sqlite3 {{.DB_NAME}} -dir {{.MIGRATIONS_DIR}} reset

  migrate-status:
    desc: "Проверить статус миграций"
    cmds:
      - goose {{.DB_DRIVER}} {{.DB_NAME}} -dir {{.MIGRATIONS_DIR}} status

  gen-sqlc:
    desc: "Кодогенерация sqlc"
    cmds:
      - sqlc generate

  install-tools:
    desc: "Установка dev инструментов"
    cmds:
      - cmd: echo "Установка линтера golangci-lint..."
        silent: true
      - task: install-linter

      - cmd: echo "Установка форматера gofumpt..."
        silent: true
      - go install mvdan.cc/gofumpt@latest

      - cmd: echo "Установка buf..."
        silent: true
      - go install github.com/bufbuild/buf/cmd/buf@{{.BUF_VERSION}}

      - cmd: echo "Установка protoc плагинов..."
        silent: true
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - cmd: echo "Установка db мигратора goose..."
        silent: true
      - go install github.com/pressly/goose/v3/cmd/goose@latest

      - cmd: echo "Установка sqlc..."
        silent: true
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - cmd: echo "[OK] Все Dev зависимости установлены."
        silent: true

  install-linter:
    desc: "Установка golangci-lint"
    cmds:
      - curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin {{.GOLANGCI_VERSION}}

  install-grpcurl:
    desc: "Устанавливает grpcurl"
    cmds:
      - go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
