[grpc]
address = ":50051"
enable_reflection = true
enable_health = true
shutdown_timeout = "10s"
max_recv_msg_size = 8_388_608
max_send_msg_size = 8_388_608
max_connection_idle = "5m"
max_connection_age = "10m"

[postgres]
app_name = "gotips"
dsn = "postgres://gotips:gotips@gotips-dev-postgres:5432/gotips?sslmode=disable"
conn_timeout = "5s"
max_conns = 25
min_idle_conns = 5
max_conn_lifetime = "30m"
health_check_period = "1m"

[cache]
size = 1000
ttl = "1s"
timeout = "3s"

[pprof]
address = ":6060"
enable = true

[logger]
level = "info"