// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPcPart = `-- name: CreatePcPart :one
INSERT INTO pc_parts (id, name, version, created_at, deleted_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, name, version, created_at, deleted_at
`

type CreatePcPartParams struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Version   int64        `json:"version"`
	CreatedAt time.Time    `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) CreatePcPart(ctx context.Context, arg CreatePcPartParams) (PcPart, error) {
	row := q.db.QueryRowContext(ctx, createPcPart,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPcPart = `-- name: GetPcPart :one
SELECT id, name, version, created_at, deleted_at
FROM pc_parts
WHERE id = ?1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPcPart(ctx context.Context, id uuid.UUID) (PcPart, error) {
	row := q.db.QueryRowContext(ctx, getPcPart, id)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePcPart = `-- name: UpdatePcPart :one
UPDATE pc_parts
SET name = ?1,
    version = ?2,
    deleted_at = ?3
WHERE id = ?4 AND version = ?5 AND deleted_at IS NULL
RETURNING id, name, version, created_at, deleted_at
`

type UpdatePcPartParams struct {
	Name       string       `json:"name"`
	Version    int64        `json:"version"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	ID         uuid.UUID    `json:"id"`
	OldVersion int64        `json:"old_version"`
}

func (q *Queries) UpdatePcPart(ctx context.Context, arg UpdatePcPartParams) (PcPart, error) {
	row := q.db.QueryRowContext(ctx, updatePcPart,
		arg.Name,
		arg.Version,
		arg.DeletedAt,
		arg.ID,
		arg.OldVersion,
	)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
