// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePcPart(ctx context.Context, arg CreatePcPartParams) (PcPart, error)
	GetPcPart(ctx context.Context, id uuid.UUID) (PcPart, error)
	GetPcPartsRecent(ctx context.Context, lim int32) ([]PcPart, error)
	SoftDeletePcPart(ctx context.Context, arg SoftDeletePcPartParams) (PcPart, error)
	UpdatePcPart(ctx context.Context, arg UpdatePcPartParams) (PcPart, error)
}

var _ Querier = (*Queries)(nil)
