// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPcPart = `-- name: CreatePcPart :one
INSERT INTO pc_parts (id, name, version, created_at, deleted_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, version, created_at, deleted_at
`

type CreatePcPartParams struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Version   int64              `json:"version"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreatePcPart(ctx context.Context, arg CreatePcPartParams) (PcPart, error) {
	row := q.db.QueryRow(ctx, createPcPart,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPcPart = `-- name: GetPcPart :one
SELECT id, name, version, created_at, deleted_at
FROM pc_parts
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPcPart(ctx context.Context, id uuid.UUID) (PcPart, error) {
	row := q.db.QueryRow(ctx, getPcPart, id)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPcPartsRecent = `-- name: GetPcPartsRecent :many
SELECT id, name, version, created_at, deleted_at
FROM pc_parts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetPcPartsRecent(ctx context.Context, lim int32) ([]PcPart, error) {
	rows, err := q.db.Query(ctx, getPcPartsRecent, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PcPart
	for rows.Next() {
		var i PcPart
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePcPart = `-- name: SoftDeletePcPart :one
UPDATE pc_parts
SET version = $1,
    deleted_at = $2
WHERE id = $3 AND
    version = $4 AND
    deleted_at IS NULL
RETURNING id, name, version, created_at, deleted_at
`

type SoftDeletePcPartParams struct {
	Version    int64              `json:"version"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ID         uuid.UUID          `json:"id"`
	OldVersion int64              `json:"old_version"`
}

func (q *Queries) SoftDeletePcPart(ctx context.Context, arg SoftDeletePcPartParams) (PcPart, error) {
	row := q.db.QueryRow(ctx, softDeletePcPart,
		arg.Version,
		arg.DeletedAt,
		arg.ID,
		arg.OldVersion,
	)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePcPart = `-- name: UpdatePcPart :one
UPDATE pc_parts
SET name = $1,
    version = $2,
    deleted_at = $3
WHERE id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, name, version, created_at, deleted_at
`

type UpdatePcPartParams struct {
	Name       string             `json:"name"`
	Version    int64              `json:"version"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ID         uuid.UUID          `json:"id"`
	OldVersion int64              `json:"old_version"`
}

func (q *Queries) UpdatePcPart(ctx context.Context, arg UpdatePcPartParams) (PcPart, error) {
	row := q.db.QueryRow(ctx, updatePcPart,
		arg.Name,
		arg.Version,
		arg.DeletedAt,
		arg.ID,
		arg.OldVersion,
	)
	var i PcPart
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
